apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: g1tehi5si-java-springboot-gitops
  description: This is GitOps manifest for g1tehi5si-java-springboot   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=g1tehi5si-java-springboot
    backstage.io/kubernetes-id: g1tehi5si-java-springboot 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: g1tehi5si-java-springboot-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:g1tehi5si-java-springboot
